# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 08:10
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import outpost.django.base.utils


class Migration(migrations.Migration):

    dependencies = [("video", "0031_auto_20181017_0922")]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="archive",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/archive"
                ),
                upload_to=outpost.django.base.utils.Uuid4Upload,
            ),
        )
    ]
