# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0032_auto_20191018_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribeLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
