# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-13 14:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('video', '0032_auto_20191018_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='VTTExport',
            fields=[
                ('export_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.Export')),
                ('data', models.FileField(upload_to=outpost.django.base.utils.Uuid4Upload)),
            ],
            options={
                'verbose_name': 'VTT Subtitles',
                'manager_inheritance_from_future': True,
            },
            bases=('video.export',),
        ),
        migrations.CreateModel(
            name='AWSTranscript',
            fields=[
                ('transcript_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.Transcript')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('duration', models.DurationField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('video.transcript',),
        ),
        migrations.AddField(
            model_name='transcript',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_video.transcript_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Recording'),
        ),
    ]
