# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0036_auto_20210726_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetemplate',
            name='delivery',
            field=models.ManyToManyField(to='video.LiveDeliveryServer'),
        ),
    ]
