# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-21 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0036_auto_20210617_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epiphansource',
            options={'ordering': ('epiphan__room__campusonline__name_short', 'number')},
        ),
    ]
