# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-02 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0037_livetemplate_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livetemplate',
            name='_description_rendered',
        ),
        migrations.RemoveField(
            model_name='livetemplate',
            name='description_markup_type',
        ),
        migrations.AlterField(
            model_name='livetemplate',
            name='description',
            field=models.TextField(),
        ),
    ]
