# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0037_auto_20210621_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveportal',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='liveportal',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
