# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-15 10:14
from __future__ import unicode_literals

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0038_auto_20210902_2241"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveevent",
            name="started",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
