# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0038_auto_20210622_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveportal',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
