# Generated by Django 2.2.25 on 2022-03-02 20:38

from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0041_auto_20220125_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recorder',
            options={'ordering': ('name', 'hostname')},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='recordingasset',
            options={'ordering': ('-created',)},
        ),
        migrations.CreateModel(
            name='EpiphanMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to=outpost.django.base.utils.Uuid4Upload)),
                ('epiphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Epiphan')),
            ],
        ),
        migrations.CreateModel(
            name='EpiphanInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('nosignal_timeout', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deinterlacing', models.BooleanField(default=False)),
                ('epiphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Epiphan')),
                ('nosignal_src', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.EpiphanMedia')),
            ],
        ),
    ]
