# Generated by Django 2.2.26 on 2022-09-13 08:04

from django.db import (
    migrations,
    models,
)


def set_initial_order(apps, schema_editor):
    model = apps.get_model("video", "EpiphanChannel")
    for p, c in enumerate(model.objects.all()):
        c.order = p
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0042_auto_20220302_2138"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livechannel",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="livechannel",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_initial_order, reverse_code=lambda apps, schema_editor: None
        ),
    ]
