# Generated by Django 2.2.28 on 2023-10-26 09:02

from django.db import migrations, models


def set_url(apps, schema_editor):
    EpiphanSource = apps.get_model("video", "EpiphanSource")
    for source in EpiphanSource.objects.all().iterator():
        source.url = f"http://{source.epiphan.hostname}/streams/{source.number}/ts"
        source.save()


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0043_auto_20220913_1004"),
    ]

    operations = [
        migrations.AddField(
            model_name="epiphansource",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.RunPython(set_url),
        migrations.AlterField(
            model_name="epiphansource",
            name="url",
            field=models.URLField(null=False),
        ),
    ]
