# Generated by Django 2.2.28 on 2023-05-30 21:07

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0044_epiphansource_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveDeliveryServerNetwork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("inet", netfields.fields.CidrAddressField(max_length=43)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.LiveDeliveryServer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveDeliveryServerCountry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.LiveDeliveryServer",
                    ),
                ),
            ],
        ),
    ]
