# Generated by Django 2.2.28 on 2024-09-19 08:58

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    LiveEvent = apps.get_model("video", "LiveEvent")
    ContentType = apps.get_model("contenttypes", "ContentType")

    new_ct = ContentType.objects.get_for_model(LiveEvent)
    LiveEvent.objects.filter(polymorphic_ctype__isnull=True).update(
        polymorphic_ctype=new_ct
    )


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("video", "0047_auto_20231106_2024"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liveevent",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="liveevent",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_video.liveevent_set+",
                to="contenttypes.ContentType",
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
