# Generated by Django 2.2.28 on 2024-10-10 14:43

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    LiveEvent = apps.get_model("video", "LiveEvent")
    OnDemandLiveEvent = apps.get_model("video", "OnDemandLiveEvent")
    ContentType = apps.get_model("contenttypes", "ContentType")

    old_ct = ContentType.objects.get_for_model(LiveEvent)
    new_ct = ContentType.objects.get_for_model(OnDemandLiveEvent)
    for le in LiveEvent.objects.filter(polymorphic_ctype=old_ct):
        odle = OnDemandLiveEvent(liveevent_ptr=le, channelx=le.channel)
        odle.save_base(raw=True)
        le.polymorphic_ctype = new_ct
        le.save()


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0048_auto_20240919_1058"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnDemandLiveEvent",
            fields=[
                (
                    "liveevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="video.LiveEvent",
                    ),
                ),
                (
                    "channelx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.LiveChannel",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("video.liveevent",),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
