# Generated by Django 5.2.16 on 2026-09-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0048_alter_input_options_alter_export_polymorphic_ctype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epiphansource",
            options={"ordering": ("epiphan__room__campusonline__name_full", "number")},
        ),
        migrations.AlterModelOptions(
            name="livetemplate",
            options={"ordering": ("name", "room__name_full")},
        ),
        migrations.AlterModelOptions(
            name="livetemplatescene",
            options={
                "ordering": ("template__name", "template__room__name_full", "name")
            },
        ),
    ]
