# Generated by Django 2.2.28 on 2024-10-10 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geo", "0022_auto_20221219_1728"),
        ("video", "0049_ondemandliveevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushLiveEvent",
            fields=[
                (
                    "liveevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="video.LiveEvent",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("list_size", models.PositiveIntegerField(default=20)),
                ("delete_threshold", models.PositiveIntegerField(default=100)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.Room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("video.liveevent",),
        ),
        migrations.CreateModel(
            name="PushProtocol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("identifier", models.CharField(max_length=128)),
                ("url_template", models.CharField(max_length=2048)),
                ("path_template", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="PushServer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("online", models.BooleanField(default=False)),
                ("hostname", models.CharField(blank=True, max_length=128)),
                ("enabled", models.BooleanField(default=True)),
                ("url", models.URLField()),
                ("source", models.URLField()),
                ("username", models.CharField(blank=True, max_length=1024, null=True)),
                ("password", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "ordering": ("hostname",),
                "unique_together": {("hostname",)},
            },
        ),
        migrations.AlterField(
            model_name="livechannel",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="liveevent",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="liveviewer",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="PushServerProtocol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.PositiveIntegerField()),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.PushProtocol",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.PushServer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PushLiveIngest",
            fields=[
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("input", models.URLField(blank=True, null=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingests",
                        to="video.PushLiveEvent",
                    ),
                ),
                (
                    "ingest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.PushServerProtocol",
                    ),
                ),
                ("variants", models.ManyToManyField(to="video.LiveStreamVariant")),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
