# Generated by Django 2.2.28 on 2024-11-08 08:57

from django.db import migrations, models
import outpost.django.base.utils
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0050_auto_20241010_2004"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liveevent",
            name="channel",
        ),
        migrations.AddField(
            model_name="pushliveevent",
            name="logo",
            field=models.FileField(
                null=True, upload_to=outpost.django.base.utils.Uuid4Upload
            ),
        ),
        migrations.AddField(
            model_name="pushliveevent",
            name="stylesheet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="livechannel",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                editable=False,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="liveevent",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                editable=False,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                editable=False,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="liveviewer",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                editable=False,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="pushliveingest",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                editable=False,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="pushserver",
            name="source",
            field=models.CharField(max_length=512),
        ),
    ]
