# Generated by Django 2.2.28 on 2024-11-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0051_auto_20241108_0957"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ondemandliveevent",
            old_name="channelx",
            new_name="channel",
        ),
    ]
