# Generated by Django 2.2.28 on 2024-11-08 21:46

from django.db import migrations, models
import outpost.django.base.utils


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0052_auto_20241108_0959"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushliveingest",
            name="record",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pushserver",
            name="recordings",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="pushliveevent",
            name="logo",
            field=models.FileField(
                blank=True, null=True, upload_to=outpost.django.base.utils.Uuid4Upload
            ),
        ),
        migrations.AlterField(
            model_name="pushliveevent",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="pushliveingest",
            name="published",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
