# Generated by Django 2.2.28 on 2025-02-17 15:31

from django.conf import settings
from django.db import migrations, models
import outpost.django.base.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0053_auto_20241108_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushliveevent',
            name='intro',
            field=models.FileField(blank=True, null=True, upload_to=outpost.django.base.utils.Uuid4Upload),
        ),
        migrations.AddField(
            model_name='pushliveevent',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_pushliveevent_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
